apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Q8bSh9wrW9D0J/wRLjFIZi2XishxfcRnCmg+3Npw1zHnTbq7OQxNusybEtI5k6LdYwu4CTA=,iv:TiUJUwC5JChj9vHKboFHcpNqC/kyiPMRGAYyDobiE5g=,tag:/JBxz3QJqYHYHoEf35IGXg==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWmt0azdRelpMbEd1enFO
        bEtOVUhoQ0dhR3Y5a2k4UW9vczJ3VzVxUkcwCjBlS1EyZk9JU2hZNnEvMllDV01C
        N3U3TlZQMHBUS0syeWN0eGorNjZZMVkKLS0tIGppK1VGUkRvRGpmRkQxejYvbDRj
        WVJ4RUJBYkNUOGEwRHhiSDNCYmsxQzAK5FfJFrxd/qQfQtRSABGEwF8rnSz2Q6Gc
        hrQzY5X6pzJWvHkh4ZPKhebsBPknVl4wVmDXUZsk3tuCteQ7bK4gug==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T14:08:32Z"
  mac: ENC[AES256_GCM,data:p6LcRee01DxKlF7Sgy59pgmpCyCMwZ6EBcC32GNgbyUoyxKjHp46JUeQlpVkKQZOy1H1WbLz56Y6Vnxn0FvdWiZMcJ124LDpN5RxUelDOWPQ2YsaedmgaDMkoUrO3MQDLZuMeKolZKN+osD49Z9qa/QfQOvQsYV7MVOKaC2iIVQ=,iv:N87CXw+7XCdGSQ9F7xDM4JGR0m0Tr8yS/E+ucS8A6sQ=,tag:Sqvzj9t+lYFgpiM/Yfi27g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
