apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:dMBsZafxi3jf8Rz26/qnEareAQIZBuC/biqyuqZaTPxWqB9F79gQIw==,iv:Oaq5IpNvXNfvP5P+3t7LefRDbMUsYDh0V6qHgEI/NVU=,tag:gCVN+B3iT3aj+HwqD3kz6Q==,type:str]
sops:
  age:
    - recipient: age197gyr0k44kycrhp9q4xqdhpchxz72f35cp8vfpnuvq2zgg9rfekq85cgla
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2aWNQdCtmYXJhcFVPS3l1
        WU94YXJzVWlTUmpnQVptR21pSmxFVHZ4b0g4CjZNQ25xREJwTDVHVUlqRUhRdWlz
        QkJsZlNnallpVm1pOHhOSWx1YWpwMVEKLS0tIEVSVUpKLzFDY3YrVWdTSi9meWR4
        dC9ySzBhbE5JNGF3czZDWDBLR3ZMd2cKhljAdW/pkx/Y/V3kacH80Lu53xFWn0y2
        Pf/O1mw3Vv1i/lxEPrzvL3rPiPHaKMxlLC8FkQFu7iWBdzA6m4YImQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T22:21:58Z"
  mac: ENC[AES256_GCM,data:byv4l3btSpMBcpZlTkCgWQNbbzmbbQ+hZfVu5gZYm+olbom5wzMaSa3OoEKGpxqBMAIULMNv2F9S13qUfthJNqbprRhl3C5jctggC1CH32y+AlzUTgPobzI8LNEK5REnRf8gp2YJ4SJlh91LRjAR/r8JUh49Z61lKoS+qbL0Ejc=,iv:X/WqufFwVOexw4P3njTaBrF8WFHG9iQ10OnOdNVxrWQ=,tag:79FdoRSvXVinqNzTs4INXQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
