apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:NEZ/qr6pn0DwoOQBHtWBLltUoqsqY5SUpQqioKZ/pAPanW2KbSIhMRHSJEipsmL/rHQHVSU=,iv:Zw3DIaRtaBrXZstsqxfw58KCrjO+g6KzlPnT8rmY3CU=,tag:aXscrCsjPAs2aBO9fYKm6g==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VE8zamppRXNJVkJXdHN0
        d0x6S29hSGxNMDFMUitXMEtpY2hIQXlzU0ZRCnFmSnlCbGR4VjNpSlI4VFE3R1VY
        NjRoanFnRGp6Q2dHM1I0Sjl4SGNVVEkKLS0tIGliU0JldUc2VmhQaDVoV1ZIYWVm
        NHRRVzFSWkVtWE9SWWxWM0xWU0ZrVlUKimBAvXiAKgIgghs6CXL/W/r6uJm7cq7b
        1RYS5qgfBeYOtw5Ac1uz4jHcB4PyOFkjL07PyunOngCpp5Dff6GikA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-11T10:25:41Z"
  mac: ENC[AES256_GCM,data:80TXuNboW03m+hbPyXjAGyyS9Rb3v5BiO9V8FCv8r7i3BuzTuIM6mbDO/dhe9/0E5Ux4wpnVliKejJyXTuwk4Donfw0N1eNuUBAaE8mfKF9Vcddc2zd6RATztUeNdvfT2orTSw0DbfWtarXX6e0XdV4UPBoYrIezJbNJvQcWgtg=,iv:je5NjJF6G9XDRH14PnHYNk2HEYF0xW39KvHkvWs7j+A=,tag:DI+n/B2AnUtm25iVkoGf6g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
