apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:YYMAePKQ1mc=,iv:Y4z3NDf+6l1EUKwfY8Dt3lN1wsrPuw7oZ4YV1enMits=,tag:3+jwm+cMluLg/lG6bXcrSA==,type:str]
sops:
  age:
    - recipient: age197gyr0k44kycrhp9q4xqdhpchxz72f35cp8vfpnuvq2zgg9rfekq85cgla
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOSm9sWE9SWkFiZmQ3UXFB
        Rk5jMDVwNGJEYld0c3NhSW9kYmJsUDc1aUU0CjRxZk94VU5kNVBxSDExeFpnaXZn
        UWlVYkdwb3RqNXNGNEpaKzJiNU0yUFkKLS0tIFVjNVJKQ1hjOG1QdEF3dEtYbGZ6
        U295eHAxOFl5eGRiRWtVQndyK1F3S00KLEBZavJD+gdF/VI46GDAsHxpYbDnMn53
        IkOnOrhhBOC1xgEHoWgxQhAdv/3qKG2wzDeDEbUnxiuLWcEGYFJk2Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T22:21:58Z"
  mac: ENC[AES256_GCM,data:+rNbZyXns5Hj+7nyBAm4s4KxaZGqGbzRV7SZbvtvB7ju0z2WD45nwMjeeOEVC6qPoG1dWtO53/+O8rcAT+mJIuHKu5KjVhLGbL4uWvgDfZvpUSjF2iQtDVFrpVQqDduXtUDeiyZhXlMSnP4ARlILYhg7hhxNfTqGJRkDF3GoLX8=,iv:WkeauAmUyRs+GNU1gF9J8dsC2a7ximhYfYbHqzLV9Bk=,tag:mzcQEcHqm6SYykJONbF9rg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
