apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:TwHkxfF62xlYzkt3mjUyPPAAhtR8Kt+n1GA0kokSo58=,iv:Zwd9Li7TcaPCV5myt1BsYtTjI1Pk4qCqehCawI5M7yg=,tag:gFiFeYUsCLYpJz5c2KLxOw==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5UXpQMGxMVVJ4akVYSHpC
        Z3ZyOEJGZll2bHN2Rm9hVzRSU1VNMHZlOTBrCkNwTXQyVEI3UHVoWTREZG5WdVZC
        K3hNdlpMOFl2dnNMWHR1REU5ZG9hMFkKLS0tIGtMeDFPWmExUG5iV3cxSFc2c21Q
        VlhkdXJyamMwOFd4ekMwRDYzSFp2d1kKbq8PhVx8f/GgTvnlKt0ZLqYAhZPWfQFn
        WY9AU5sbJTvFx0mINcdmhJfqCE0C/cnjAEbZsaDjjZB9ZM3yTEBlVg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-11T15:50:45Z"
  mac: ENC[AES256_GCM,data:IhpGBY3Hk3vvsXhbUy/THmLgHYdixxwxWiGpgwE4hL5yuNv7O/ehk6J0jdWKIYfw2V/C5gHFbbHvF1t/zSS95ZYdFT6g7tqTlh+0KjXapNmtXd3W4+Heah3k9jvyQ3Vof9WVgQNSO09p381tIOSxfRkJBXoQ7MYRL9v0f09RSRE=,iv:QTG43iaej3HEVYzsTDUFb+/Cz6oqFzjJ4LQ2Z7FES6s=,tag:ePru89MLyCksxkPMwkr85w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
