apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:w76V7geI55r06Yr9EQGQsHVHpPZnASqRxl/w8dlhB3c=,iv:DQECJ2qW1IjSTX11PfdfYgAxLP3rNC+dPJS9pRLnSIk=,tag:llP87n2gxbolvvd7/ZM2Ww==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDQ1JFQnVieTdIYUZNaDB0
        WmxqUWFlOE9nRUVNaWlhY2xybjNFNjRVSm00CjBCS1Zmb0hXeTNsRHZ5OWZMdlNX
        azNGd1gyK2RDYnROclF5Snd4ZGsvOE0KLS0tIDV2V3Bpa3hEWjU3WGUybFRkMXZR
        WWFHYmd0dHpYVU44QmtIRGVpT2paZUUKLLNZD18Vv9LeE/FJ39/ShSgSN59KfOYP
        QeDLvEUEDMTGIeJzbW0vaO85HWfjaj4dZ60TKvXygayhw6HHJn1JIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-11T10:25:41Z"
  mac: ENC[AES256_GCM,data:rPJI+ZjOHCiLrsXSO2NaROMX82NsSLCxR8iSY5xrjEsoX/eiiBky3339EhupoitsdIgzjkZ9i1kacZdtHZwJFBu5OgwI+JkG1cEIQ8f2VwO3IexusKLljiqlQ/AjgjPvzM6Kh4PGrUrdVmbq9PheKGkeUuifFU9aCbinGZ/JoUc=,iv:fUKkz8BMktGKsbKX5KPtB6E0iXzirPtNJpMbl6GQQpE=,tag:poxc4zLXTuPvkYaSgqgTwg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
