apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:l1A/8QmIFqcuIPGTHmL3zfD77xIXhHIo+tK/EDSE4Tw=,iv:U1s1hO4zznh7CxrXwDt/5LPVWd6BDfuMvDLN+++hcso=,tag:PnWeETrOyNygKHFCiyzsyA==,type:str]
sops:
  age:
    - recipient: age197gyr0k44kycrhp9q4xqdhpchxz72f35cp8vfpnuvq2zgg9rfekq85cgla
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6cFhXUzZzYlBQeXlIZnQr
        REMxeVh3YlYwTUZlMnVGSWd3ODVjQ2pUdHhnCjVUMnVPZ3pxSWdGV0ttN3kvSVUw
        MkpaS2YwZjlpL0ZpQTFnTFdCMWJ6N2cKLS0tIFpwQWVJTENQbzgwaWcyM3R2Q3JB
        UGFSaWtMTFE2d3VQNExQc2FRU2ZzNUEKvJfm009mQn4ZdijHYfdghsttF1coJw44
        NlFjH00NgHXDG6v6De8sqfQJEPLZN06Fdqcb08yhIo9Rrhdc1HfUZw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T16:47:41Z"
  mac: ENC[AES256_GCM,data:c8HnNg2lsazVr2bw/SmNljeEpqcc3kuoHnjutk+C7/ZgLCw7sCoMMR+X0GI7t9vteo9HvNgXHcwIdNbJ6AWIkTdy9kKKO4zjtzQA72uoaYt6IDP6bdZjQQucLVBx13pAf82DFBFnZSpGPf7a7tMC2Twi3hqz1zcF2zRDBZ2viXk=,iv:YbGZIGkoZ4IBs+rSQIGaIDozfHP9anJ5KqEndZXgOm4=,tag:YEnSVqlwxhJkX+sKXUyNxw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
