---
# -- API Token for Cloudflared default lan tunnel token
apiVersion: v1
kind: Secret
metadata:
  name: tunnel-default-lan-token
  namespace: network
stringData:
  token: eyJhIjoiMDU1YmM2MTMyOGRkNGQyZDRjMDQyNWNjN2FmNDdhY2UiLCJ0IjoiYzkzMWE2YWEtNjA3YS00YTZlLWJkZWItNjY0YmRiYWJhNjdkIiwicyI6IlpqSTFPR1EyTVdRdE9ETmxaaTAwWTJOaExUbGtZV1F0TVRJNU1XVXhOVGswWVRkaiJ9

#docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token eyJhIjoiMDU1YmM2MTMyOGRkNGQyZDRjMDQyNWNjN2FmNDdhY2UiLCJ0IjoiYzkzMWE2YWEtNjA3YS00YTZlLWJkZWItNjY0YmRiYWJhNjdkIiwicyI6IlpqSTFPR1EyTVdRdE9ETmxaaTAwWTJOaExUbGtZV1F0TVRJNU1XVXhOVGswWVRkaiJ9