apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://omni-k8s.janncot.com
    name: jcom-jiahd1
contexts:
  - context:
      cluster: jcom-jiahd1
      namespace: default
      user: jcom-jiahd1-ferry133@gmail.com
    name: jcom-jiahd1
current-context: jcom-jiahd1
users:
- name: jcom-jiahd1-ferry133@gmail.com
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
        - oidc-login
        - get-token
        - --oidc-issuer-url=https://omni.janncot.com/oidc
        - --oidc-client-id=native
        - --oidc-extra-scope=cluster:jiahd1
      command: kubectl
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
