apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: https://omni-k8s.janncot.duckdns.org
    name: kmp-omni-jiahd2
contexts:
  - context:
      cluster: kmp-omni-jiahd2
      namespace: default
      user: kmp-omni-jiahd2-ferry133@gmail.com
    name: kmp-omni-jiahd2
current-context: kmp-omni-jiahd2
users:
- name: kmp-omni-jiahd2-ferry133@gmail.com
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
        - oidc-login
        - get-token
        - --oidc-issuer-url=https://omni.janncot.duckdns.org/oidc
        - --oidc-client-id=native
        - --oidc-extra-scope=cluster:jiahd2
      command: kubectl
      env: null
      provideClusterInfo: false
