context: jcom-jiahd3
contexts:
    jcom-jiahd3:
        endpoints:
            - https://omni.janncot.com
        auth:
            siderov1:
                identity: ferry133@gmail.com
        cluster: jiahd3
