apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:wnicL5oJscY2dk5kelvMlDVVfrPd/i5r/EcDeKIKIs4ZtHLPUsNrFJItH3Eswb0n2CRJIlBicb7X6yZqA0Z9JXDAX6JPo8B/xGGndIfsQK0vQpZ1mfdpKFsyk3PlZMGGc5uAMJSwN8F6O4U2dZZ5VLTIYc5m9vmxup5B5j9dtxge4Kbe7nYGg+iBfalSlvxiJhdQ31gYXCz6hzoRGxj96oMbnmT3BhsvKLzdB2NB+DS7a8FQ,iv:NLaDF3KsFQQW3pItRHXuQWdVZZ5OTIC1C/MkZUsJBE4=,tag:GKWbxi/qScZjygNkFoQiYw==,type:str]
sops:
  age:
    - recipient: age197gyr0k44kycrhp9q4xqdhpchxz72f35cp8vfpnuvq2zgg9rfekq85cgla
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSVTFieXJycjk3dUo0dFNG
        QVZvRklLbCtGdEo4UmdyZ1NSWERmOVRmL1UwCmtRQnBqa1pmS2xJeFpQZmNSd0VW
        WVZwR243U25NNDQzeTlLMXVLVURoREkKLS0tIHh6MFZnc1pOYlBzQ1dBd1lHU0h2
        c1VLRDkrTkpDczVHdkRESHZWVFU1N0EKTTv5fLHp7xrI1fueYsD4cypB5J27590C
        lr2s3E28kC5MlMa7W7Wm71lH1aor1gpP+A/cpNKPS4geY6i+0IEt5Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T22:19:45Z"
  mac: ENC[AES256_GCM,data:M1vpDNrCFs/+nK43R2Q3JnJkGXa0DZoy2IJTx7rptLafRN8Dh6iExk18Fe98N4Q8YcTfXMi/fvvbZTtBkkOxG559sKrcsQUsVk8V0UpzYWaOwN/VLHQ+NpMkaYEuvLKY8wUFSGXg5DfI9Y/XEkyA5gG/Ax4awnuFqqbzNXKyc98=,iv:n9wEhhs6K/gVEK4qxVrmfIaZQwiQRRP5cbAQBW9t9IY=,tag:BU69Nsb+p5GrZuwSFCiS2w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
