apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:nP8hHiSi1hxym1MVqVDQJWklIL20wXa7cNY9jGulbj+U5vau1WQqhD5fIKJTQ7mWV3mYV3lpV41faj7B29XdDeSgYJpjlTB+pr1sHTMJy8/tw5j/9Gjq7LeO7HQO1nhmHrk8+VaXeM57VC+JPeSpcljPkqbATV04SfDbF3c4jaW9xmZsNnft8eeEtynWh82zh47KbSChcX2ddYd3K1FeSpZ3cwKLzdpmX8hi9OglXaofkFpz,iv:ZfFLP5HCd92bBL7iYrm1bUTI9NYlGVyDncg0vKHENQQ=,tag:EgoI5ffU5b0lzV19xABftg==,type:str]
sops:
  age:
    - recipient: age197gyr0k44kycrhp9q4xqdhpchxz72f35cp8vfpnuvq2zgg9rfekq85cgla
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVWx6cWZDeVFhbFZXaUxr
        RkdFNW90VmpTZzFIelBSemQ5T3NGdlRGQVhVCm8zL2N5Q2s1a3dVRFgvN2xBalZJ
        MFJraGF3YS9DOFpUY2xjdkU2WkpoTkkKLS0tIE9KTzIyWUJ0VEwvcjlPd1c0Z3pj
        Y1dHTW1ROXVSQ3pOR1lnRklZOWtaSE0K82PVdUnZZ7KhKNuW+FwWJ7BTiKjhNYtL
        ryk6rZv1wKqr9uOiRNChCsd4yWy1E9BFZyeFDoWvFtbhd94ip1GLPw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-04T16:47:41Z"
  mac: ENC[AES256_GCM,data:Cq0KjxdIAJtFl6NISRO1DMEM4KkmR4CRR7vsKHx+CB3VeVxvzLbpZ06eBGphGYNYeuq3DjT6/ElbBYVCeL0zOZG3ao0yKanbYkv1DvJo9cv/XMIyXigyFJloob+mVIG+7GdlvDEkbeJHctzhzr1ilFgoSWz5Fvkz1foUQcp+P0I=,iv:Z6qTS2GUyL+W1OF+Xxe28qTOyYgAjvCItj64s3YvnCU=,tag:vn9jPAS8eTG05VMlMfbQTA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
