apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:L3/n3zY7GfXRMU0fH7iwojbeX8paceT+B6tB/5J+6LLO48mfrrSvC0VQ1Y8b3V0l7Z2+U4tHxcch5PzX6OW/nUwUhrMsE1Jgj3LGb+6FC0LTsi0S3Bx76sUxnrbr+lnANtI4VnQMUokd91pBkNSr7Pke4tqbVEIGXVdoujWbrB6R07LtrXo/ucCas4lsV1o6EnRDVikB06gTCKvRR8F1816wGTdDUW3ayXYfATYdjxUjh9pk,iv:Ah7fIvPuFhNwgsMjk+9hUDI1T1NRScCLKlucw9PGJw0=,tag:SBNnsbJ9Cd20RKj/IwUR6Q==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodXRDSkhyYkV3U2NQQUpY
        dzZiV280cFg3UFBwdTlRSzRlVXZ1NDZpSGpNCk5YOUhrVGFUdDc1YzluM2IyMjVF
        cVlaUjZDYnY0NnJmNDZsMjNab2wyT1kKLS0tIHN0KzV2MjRENmV6c0VxUGJMdGJD
        dkMxS0F1ZUJhaXYzdnZFS1hLVVYzOVUKmFblIfHDo5GeiPfmI/bIM4GzuhATZplm
        SET9JEn2nX+9aWTuGkTBoQrS/RqnS3IVDBQLbkfLztDZt2289at8NA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T17:50:49Z"
  mac: ENC[AES256_GCM,data:02A8YUh1XkUxapfUWbFruUDAwk9IOo5o204FJFRTaI31TRbSHKzz7WOpRte0yJsf7tOSEseVOSHbKf670UHmFU7fiPUaY8Na1bxT6V6sskAcCmb7gIywcLJR2/SgNm/c3ggQmVS+XPocj9+ytAdbiH8vLcgVk43PSeWWy/pB7yg=,iv:Icv4wwKUpNVm3zfZRZndF/BorlETstp5VC5/5/Tfx3k=,tag:pSr6RpQJe/zxEJ1aotQeNg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
