apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:q9DgGfTqhYvsZaPql5ReKHNRDQjmLD08Sv92Mkyh4PHKNBPBpIU3I5wwHdRBD0I9s6zC+NE=,iv:R1fivaANWD4/SeTEUE6F91wDAay3mw+8Ak9xcX+Ct5Q=,tag:LNCMZVHiTwVZLJP28ZqK3w==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WWdyNjVPYyttaDZEWG91
        TXVnUHF3eHRVQ1o1c1J0NW43TStBNEhFWG5VCjVTeTA5NlZ5NDlRSXVIMTBSWkc3
        MHcvV0xJSk1uT3Nna3Q4YWVSNFIrLzAKLS0tIEdqb24vNUs3Q0xIeGdndVdNTUw3
        QVVOSUNVTXNQN29TdWxZQktjMEUyK28K2ltfKqLtd9mRRSz4nWSTx1KTk//AVzCw
        cgRfsNJ+DkVtO0Xisjzo5ljePavxl9zCGjmXTABMgoyybPVKlRUPUg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-20T14:08:32Z"
  mac: ENC[AES256_GCM,data:P6N0R+Fp5lDFfXfRg+GSqHg6KVlMjQuVENsG4HuwFodTGvaBp+/sGqpisPXSDbx2wxu6LE7h7SA33qYwYcvbKgEH/n8tYV67VjRl+R/qjdUywNkcRtAVh9xWQg5t7Rs5mqPfdPcACLK9vaPdvbwFmVj2KEJJp7f5wO29F4uHOSI=,iv:n/P5jyoTIsyVOP1nB9fN/25QrzzUH+i1tlbg/9bo/hg=,tag:aN8uVg8dCV9Fm9pOV/wVNQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
