apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:DRz8txIm7tRPi0tAcgZ+piCXyYM50OAitdBF8JXZKZAIIaUkn74cc19POBJjxv6a6ZEe8Lc=,iv:aaEUAfUy9BVMobWE+BZvFOZ9CkciXtSGKuvycURivBs=,tag:Hcxl2DNKVDXyfveBXjnn0w==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTTZQNFIybnNienl0clU5
        dy9Pam0zdis1TDRVQW52VUlNZm4zSVByOXlJCm5NMDBJMDdORE95c1h3MDF4VU1p
        ZWp3NlNVRXc3RFF4Vzd1b0FnVFZqNGMKLS0tIGwrS1F2SmlNTHNlU2hMdVEzaXUw
        Y3lxZlNjeEdnWDEyOXRpYS92YXpQYVUK6Uifz/SEVJ1KlBqXUmSjtxzUR7rwIMYy
        rI0PfrcpMiO9UQJwoIymt3fd0oEoQVCCzPnvmSdNeaNvuq8kvPPpgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-11T15:48:35Z"
  mac: ENC[AES256_GCM,data:lOvLvXj4wBd3NEAAF9YSUq9LbvtclZ0ebvEDyrUxSBmnRPtQ4cUHrNzNzSpg3CeKocppPxXFC2pqhhBxamJnWpTv8NXnVoPktyJooF862IHPll1NDdWcrb+DcEyfPy067YNRKEaxLtf4ZuyCE1ee7d/RDiKyYCibz7zxoJjQ1MY=,iv:fTNWU1hCqtbj6MRQuHP5TXxAhRBatGSo70MegZgYHQQ=,tag:V/ekXHnRi0LJsrm6eLhkVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
