apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:Rcu9J8m5ER4iMM1CsPYV5IvLBo79tDMrDMHMXczXe8nt5Hn5OtUZKg==,iv:4cpNTCxCwXyberNKFocYcFmoHQXfMmPUwftf04JMmCI=,tag:QRAxq5H7LOB3XKZofWHmWg==,type:str]
sops:
  age:
    - recipient: age1t2ae5ddm6pgagaprtek4ncwkxpqtlccm2qade5hkh89llcc30g9q34laf9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTcFVqTExaRnVsWDIvMU5p
        TXN6V2VIMTlEZUNYcUVoVWZuVnFtVWpEc1h3CkFuQ2ZuRC8wUkM4OXQyTkZIV0xG
        aWdmSTBNYVZYbm9yZGZpRG5FUU05UFUKLS0tIE5NS0dWWTZQRGZxSmlEc1cyMEFV
        ZzljcmJ3bFFJSVR2SUdEd3VSQWRDRjgKmVKgjhR1fOWnc8XsNKsRw8FOHlobyqw8
        fp72mSXTsH1BYZ3TUUsEAn0+G9lXxdUPBC98ZHeozHPS4JFAgFNqwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T14:58:18Z"
  mac: ENC[AES256_GCM,data:bAeoED6yE4eoBhuudQ8JOYAp16kjQwCD5Jl8AHcb/4Pr0ugZhxpBapS68WOGDkivT5U9FB1zAzROVrxqejhC5NX/OR9bl9WB/qtm7+aNmMAqXdU11L8lU7KlcbBMocl/LkP0sN2anluUh8PLZEJtuoYzE9NrLQ8Y3St4jJgjGlU=,iv:GFlrb8S0Wek3OvPUZmrRJAa0PLp70e4QljqFQS22Moo=,tag:apJf4vwRDlU01B0EXQG2uQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
