apiVersion: v1
kind: Secret
metadata:
    name: trello-notifier-secret
stringData:
    TRELLO_API_KEY: ENC[AES256_GCM,data:4Ybxc6ZohezBeWkzlG/grczY94dEBRfo8VL6oq9biq4=,iv:8fdhXRS9VycG9ulmgqjpZviqL2uA44eNZ4TMAhOH4AQ=,tag:5LhZ8FbcDQoBewhttGyMfg==,type:str]
    TRELLO_TOKEN: ENC[AES256_GCM,data:j76SDuH0H3KIs976sdN0WeB+L0kDbIaTmCxeMkpt7tvzLmVWSz2x60pdAIE88MRHx3qEPFtfgT+4NR7KIRJKEmDC44O/gVJg0OqQPQ==,iv:rzJAHe0TUSp47eCuDyX7SHiZX1o4MY+Y3zXzqpVaiMY=,tag:b/wmwUBJoPSzxpknlTxp1g==,type:str]
    LINE_CHANNEL_ACCESS_TOKEN: ENC[AES256_GCM,data:3EL+8deAnLCt7AcvIJ0Xm+oX95O4muXVhI0urRE+YKGA7LvG8NGtyeFIrmXSbWwIpaBOUVzyVXU6VzpBXFvmTATRrbf6GzXXHao49hnNrpXYQWFiaJ+ZU+I51evXI95B1ihi7NYnC1ucdlCNjO3e0/RWrQa0MqxCEeJ9Hs2ja/B6XHw+M2V6SDxCErnrnRVgT5SWtDZlwbIIMvBhtOkscBwsNnOvwQqfvyKAWQ==,iv:HKx0g91TIBWi4OIQxwAda4WJ3NAQPfoQFH0VFPeJHmw=,tag:pNIs1oxPo0xd8Tkh2ChrJA==,type:str]
    LINE_CHANNEL_SECRET: ENC[AES256_GCM,data:5d8FUxcD9OwFZ/rUsQRGOr1cQV1jpRE8VvckiyGSXiY=,iv:Ffb+z7icv79Lbap1MpZ2lk2MPJP7cw3UpTSbCDQevMc=,tag:mvMPCQ5sgdjcwEatTmbiSA==,type:str]
    line_contacts.json: ENC[AES256_GCM,data:OWZJKjiGGotEtBluW3FIM2bpl8hiaBPk+Y01+c5NNVRz9+z7qgTHJgqT+AMOeTK63R6L+oZ2YcR+IZ2UUN+owDjd3orXli9fySnIIRLo9A3ieWBqOEngOgPCeUPsE//Gkvl7N3fElYpfFuyWkzDWt4zJmKfYeUjsD9HeKg1IM6fMYK7NAeEn8GeUnd/2QObHm1a3iZE+OH3Ha/7E2UeZMRRoYlnjwFj5JO/mWS3MvIc4Y/3Q0Anuswq4PAIdPYWTUnpF6D8xkQ29G4yq2ZJQFf9OR5fMB1ipG8EJJdOq/Vpp4X3zpXW4r1MebBfX+p9zuIFRbO4=,iv:epr+uYwsf0BGd/S16TOjngDmQ2qdNBeU0Qm7HI2zIHQ=,tag:nkqJLu78b8iFdrzMMlA/eQ==,type:str]
sops:
    age:
        - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVCtDR1VQZHJVUU11dDlS
            MXhoVUJlZXBnS3ZudmI5NlV6R20xMW9mZVM4CkFBZUdOZ3BoL1E4MVlJMUhaNnFS
            Z2ZpZWtjOXRDNE52TkI5VEFIa3BWcGcKLS0tIEMzTkZmWURBWUovQXJDRndkY0hE
            KzVxb0FscExDVytmY0gyMVFaYTRZYW8KDJA4Ev7epgcrAsWlk5MIIMsatXIsozae
            bUXdMnPLDJc0P69nvm3R992+5ks06y53eM/i04F1R6reHOcFSpY1EA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T13:26:53Z"
    mac: ENC[AES256_GCM,data:wyjqxG8YLMUCqL2my/Gxo0OzBTdrolMJHaDtlVjNz2ClGcLFkQQISzlvRgH39N84L6VrWo3Pz44Q1PCU5aICWutxLIeoYRjnUVECWWAxHXDN4wZL0LnxwgncjIqmEJUcCq0lNo3iCINElOURNytBecnIWBhAuNZqqJ1yyy8OXiU=,iv:CIWRMNW61xP0T0JyDO68ezOYbdWPUJyFPA6OLpNqPpo=,tag:WRIg/EHeAoQRA9nrCDjsjw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
