apiVersion: v1
kind: Secret
metadata:
  name: trello-notifier-secret
stringData:
  LINE_CHANNEL_ACCESS_TOKEN: ENC[AES256_GCM,data:2OLbDfxJiTjbJaiv+1g1+RdZuMLhLXg2yJXvrLZFike80k5ggX20x/kDgARe9znezzRl0njK+spD5W8Y1H69XfXcuCtTTrWJEY3KyegtqVu/X6uifS62/Z1WJae8ca9ADISsukHvlFrm3VxSiGXG8ToTrot79d9VVwBNHoCS4fJJ6nkXYAVHNtsMNwMdWJW68SxMKeQxF2xG65KE6OMEKpMMF8u0Lji0Epxovg==,iv:sq1v3m0IgBUMSnH4sqp1jq6FrCdHUtfp/+I8vhPPrz8=,tag:/iCKsjE3pBkmgsdr39rDJQ==,type:str]
  LINE_CHANNEL_SECRET: ENC[AES256_GCM,data:otJHMeDu/jQGUqkwhZZB8QofvWH0qUT4a5ork0s5KQI=,iv:PG+kWx/cDeygAOQscdTpSB4q8I+DnYmU5ut8TuW1bBw=,tag:epNT1/kXlP/msgv9q5TD5Q==,type:str]
  TRELLO_API_KEY: ENC[AES256_GCM,data:+erLn+28T9pTavXn/MaWBSafbwnIodpIC+AbVXoZfTI=,iv:m/5GtSjjm4Us57fMAbbFKqBO3cJbft8AQcy6UWXMM90=,tag:dx0qIQw8UEuP4iXCRnkkTg==,type:str]
  TRELLO_TOKEN: ENC[AES256_GCM,data:8ph6QD1u/DJYx/l/bz1ffVRO1fyVS4K2TpdWjBIXTbalr3O75rURviwz/+GyHQiH3XWtbal1/CxceRjFPrj8H0LkxVtsCqW2B78TXQ==,iv:Zqg4Fp1ft8eW6xA0OrDn7y2cHhs9PUhwmzClhpR0ycI=,tag:P0tZpsz0NTXBB2KjnWMohw==,type:str]
sops:
  age:
    - recipient: age1qzqxcn87tv7yt2e7vgaxcgx3reh9jczdeda4f6l208tlth0k75yse2rxsk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2WVZobjZPN004M0o1RDMw
        dEZRbENmOGhCMEhCbnlNd0c0UEJBZjZ1MkVVCmtkS2h5K1lJRGEyc3dzbEtkN1B5
        WjF5cGRxQW9Gc0N0VklTeXdMYnhhUmMKLS0tIFNmcnZvNEtkNW1qc3VxN2lFS1RU
        Q2paWms4Uk1zZ2tMdE12b2ljaXdSMG8KJ7wPCurxsq9rOTKmsVtQMCKSt3QK2H8j
        yj10GWJdHiZdxMLUo6VHL2I9B5d458BjZ22/NkRnRxqqxnWIc7c/XA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T16:12:08Z"
  mac: ENC[AES256_GCM,data:4T7vWL+S8mqgJFgUEwNouUNYTY5dcJvzK1exbNA4cqf4UGnUYrt633+nYMj88QdDDahlDZz4LIlAb28y7r1YMd+u/MuRvABpW3UtrKrHuJzB9XzvmdTFv71Dd/e/RQLJRmj+kk4Ynk77YsDEl8E7I6tUHDqCgWCFqM1PDaZQn4M=,iv:o04KylGv+TjVuF4oL3dsL96UPoNTUj7jcNlZEUwHk6E=,tag:Qz9RzbQwcixm3iHQ2JCkvA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
